using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System;
using System.Collections.Generic;

using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.Net.Http;

namespace restapi_konzolos_countrie
{
    internal class Program
    {
        static void Main(string[] args)
        {
            var countrieData =getCountrieDatas("hungary");
            Console.WriteLine(countrieData);
            Console.WriteLine("Program vége!");
            Console.ReadLine();

        }
        static async Task<String> getCountrieDatas(string countrieName)
        {

            using (HttpClient httpClient = new HttpClient())
            {
                try
                {
                    string apiUrl = $"https://restcountries.com/v3.1/name/{countrieName}";
                    HttpResponseMessage response = await httpClient.GetAsync(apiUrl);

                    if (response.IsSuccessStatusCode)
                    {
                        string jsonResponse = await response.Content.ReadAsStringAsync();
                        Console.WriteLine(jsonResponse);
                        var countrie = Countrie.FromJson(jsonResponse);
                    }
                    else
                    {
                        Console.WriteLine($"Hiba történt az API hívás során. Státuszkód: {response.StatusCode}");
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Hiba történt: {ex.Message}");
                }
            }

            return null;
        }

    }
    // <auto-generated />
    //
    // To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
    //
    //    using restapi_konzolos_countrie;
    //
    //    var countrie = Countrie.FromJson(jsonString);




    public partial class Countrie
        {
            [JsonProperty("name")]
            public Name Name { get; set; }

            [JsonProperty("tld")]
            public List<string> Tld { get; set; }

            [JsonProperty("cca2")]
            public string Cca2 { get; set; }

            [JsonProperty("ccn3")]
            [JsonConverter(typeof(ParseStringConverter))]
            public long Ccn3 { get; set; }

            [JsonProperty("cca3")]
            public string Cca3 { get; set; }

            [JsonProperty("cioc")]
            public string Cioc { get; set; }

            [JsonProperty("independent")]
            public bool Independent { get; set; }

            [JsonProperty("status")]
            public string Status { get; set; }

            [JsonProperty("unMember")]
            public bool UnMember { get; set; }

            [JsonProperty("currencies")]
            public Currencies Currencies { get; set; }

            [JsonProperty("idd")]
            public Idd Idd { get; set; }

            [JsonProperty("capital")]
            public List<string> Capital { get; set; }

            [JsonProperty("altSpellings")]
            public List<string> AltSpellings { get; set; }

            [JsonProperty("region")]
            public string Region { get; set; }

            [JsonProperty("subregion")]
            public string Subregion { get; set; }

            [JsonProperty("languages")]
            public Languages Languages { get; set; }

            [JsonProperty("translations")]
            public Dictionary<string, Translation> Translations { get; set; }

            [JsonProperty("latlng")]
            public List<long> Latlng { get; set; }

            [JsonProperty("landlocked")]
            public bool Landlocked { get; set; }

            [JsonProperty("borders")]
            public List<string> Borders { get; set; }

            [JsonProperty("area")]
            public long Area { get; set; }

            [JsonProperty("demonyms")]
            public Demonyms Demonyms { get; set; }

            [JsonProperty("flag")]
            public string Flag { get; set; }

            [JsonProperty("maps")]
            public Maps Maps { get; set; }

            [JsonProperty("population")]
            public long Population { get; set; }

            [JsonProperty("gini")]
            public Gini Gini { get; set; }

            [JsonProperty("fifa")]
            public string Fifa { get; set; }

            [JsonProperty("car")]
            public Car Car { get; set; }

            [JsonProperty("timezones")]
            public List<string> Timezones { get; set; }

            [JsonProperty("continents")]
            public List<string> Continents { get; set; }

            [JsonProperty("flags")]
            public Flags Flags { get; set; }

            [JsonProperty("coatOfArms")]
            public CoatOfArms CoatOfArms { get; set; }

            [JsonProperty("startOfWeek")]
            public string StartOfWeek { get; set; }

            [JsonProperty("capitalInfo")]
            public CapitalInfo CapitalInfo { get; set; }

            [JsonProperty("postalCode")]
            public PostalCode PostalCode { get; set; }
        }

        public partial class CapitalInfo
        {
            [JsonProperty("latlng")]
            public List<double> Latlng { get; set; }
        }

        public partial class Car
        {
            [JsonProperty("signs")]
            public List<string> Signs { get; set; }

            [JsonProperty("side")]
            public string Side { get; set; }
        }

        public partial class CoatOfArms
        {
            [JsonProperty("png")]
            public Uri Png { get; set; }

            [JsonProperty("svg")]
            public Uri Svg { get; set; }
        }

        public partial class Currencies
        {
            [JsonProperty("HUF")]
            public Huf Huf { get; set; }
        }

        public partial class Huf
        {
            [JsonProperty("name")]
            public string Name { get; set; }

            [JsonProperty("symbol")]
            public string Symbol { get; set; }
        }

        public partial class Demonyms
        {
            [JsonProperty("eng")]
            public Eng Eng { get; set; }

            [JsonProperty("fra")]
            public Eng Fra { get; set; }
        }

        public partial class Eng
        {
            [JsonProperty("f")]
            public string F { get; set; }

            [JsonProperty("m")]
            public string M { get; set; }
        }

        public partial class Flags
        {
            [JsonProperty("png")]
            public Uri Png { get; set; }

            [JsonProperty("svg")]
            public Uri Svg { get; set; }

            [JsonProperty("alt")]
            public string Alt { get; set; }
        }

        public partial class Gini
        {
            [JsonProperty("2018")]
            public double The2018 { get; set; }
        }

        public partial class Idd
        {
            [JsonProperty("root")]
            public string Root { get; set; }

            [JsonProperty("suffixes")]
            [JsonConverter(typeof(DecodeArrayConverter))]
            public List<long> Suffixes { get; set; }
        }

        public partial class Languages
        {
            [JsonProperty("hun")]
            public string Hun { get; set; }
        }

        public partial class Maps
        {
            [JsonProperty("googleMaps")]
            public Uri GoogleMaps { get; set; }

            [JsonProperty("openStreetMaps")]
            public Uri OpenStreetMaps { get; set; }
        }

        public partial class Name
        {
            [JsonProperty("common")]
            public string Common { get; set; }

            [JsonProperty("official")]
            public string Official { get; set; }

            [JsonProperty("nativeName")]
            public NativeName NativeName { get; set; }
        }

        public partial class NativeName
        {
            [JsonProperty("hun")]
            public Translation Hun { get; set; }
        }

        public partial class Translation
        {
            [JsonProperty("official")]
            public string Official { get; set; }

            [JsonProperty("common")]
            public string Common { get; set; }
        }

        public partial class PostalCode
        {
            [JsonProperty("format")]
            public string Format { get; set; }

            [JsonProperty("regex")]
            public string Regex { get; set; }
        }

        public partial class Countrie
        {
            public static List<Countrie> FromJson(string json) => JsonConvert.DeserializeObject<List<Countrie>>(json, restapi_konzolos_countrie.Converter.Settings);
        }

        public static class Serialize
        {
            public static string ToJson(this List<Countrie> self) => JsonConvert.SerializeObject(self, restapi_konzolos_countrie.Converter.Settings);
        }

        internal static class Converter
        {
            public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
            {
                MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
                DateParseHandling = DateParseHandling.None,
                Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
            };
        }

        internal class ParseStringConverter : JsonConverter
        {
            public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

            public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
            {
                if (reader.TokenType == JsonToken.Null) return null;
                var value = serializer.Deserialize<string>(reader);
                long l;
                if (Int64.TryParse(value, out l))
                {
                    return l;
                }
                throw new Exception("Cannot unmarshal type long");
            }

            public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
            {
                if (untypedValue == null)
                {
                    serializer.Serialize(writer, null);
                    return;
                }
                var value = (long)untypedValue;
                serializer.Serialize(writer, value.ToString());
                return;
            }

            public static readonly ParseStringConverter Singleton = new ParseStringConverter();
        }

        internal class DecodeArrayConverter : JsonConverter
        {
            public override bool CanConvert(Type t) => t == typeof(List<long>);

            public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
            {
                reader.Read();
                var value = new List<long>();
                while (reader.TokenType != JsonToken.EndArray)
                {
                    var converter = ParseStringConverter.Singleton;
                    var arrayItem = (long)converter.ReadJson(reader, typeof(long), null, serializer);
                    value.Add(arrayItem);
                    reader.Read();
                }
                return value;
            }

            public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
            {
                var value = (List<long>)untypedValue;
                writer.WriteStartArray();
                foreach (var arrayItem in value)
                {
                    var converter = ParseStringConverter.Singleton;
                    converter.WriteJson(writer, arrayItem, serializer);
                }
                writer.WriteEndArray();
                return;
            }

            public static readonly DecodeArrayConverter Singleton = new DecodeArrayConverter();
        }
    }


